#!/bin/bash
# Test script for OpenBMC build system validation

set -e

echo "========================================================================"
echo " OpenBMC Build System Validation"
echo "========================================================================"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "${SCRIPT_DIR}")"

# Test 1: Script syntax check
echo "[TEST 1] Checking build script syntax..."
bash -n "${SCRIPT_DIR}/build_openbmc.sh" 2>/dev/null
if [ $? -eq 0 ]; then
    echo "✓ Build script syntax is valid"
else
    echo "✗ Build script has syntax errors"
    exit 1
fi
echo ""

# Test 2: Execute help command
echo "[TEST 2] Testing help command..."
OUTPUT=$("${SCRIPT_DIR}/build_openbmc.sh" --help 2>&1 | head -5)
if echo "$OUTPUT" | grep -q "OpenBMC"; then
    echo "✓ Help command works"
else
    echo "✗ Help command failed"
    exit 1
fi
echo ""

# Test 3: System requirements check
echo "[TEST 3] Running system requirements check..."
"${SCRIPT_DIR}/build_openbmc.sh" --check > /tmp/openbmc_test.log 2>&1
if [ $? -eq 0 ]; then
    echo "✓ System requirements check passed"
    grep -E "(\[SUCCESS\]|\[WARNING\]|\[ERROR\])" /tmp/openbmc_test.log
else
    echo "✗ System requirements check failed"
    cat /tmp/openbmc_test.log
    exit 1
fi
echo ""

# Test 4: Verify hardware specification file
echo "[TEST 4] Checking hardware specification..."
if [ -f "${PROJECT_ROOT}/hardware_spec.txt" ]; then
    echo "✓ Hardware specification file exists"
    echo "  - Size: $(wc -c < "${PROJECT_ROOT}/hardware_spec.txt") bytes"
    echo "  - Contains $(grep -c "RK3568" "${PROJECT_ROOT}/hardware_spec.txt") references to RK3568"
else
    echo "✗ Hardware specification file not found"
fi
echo ""

# Test 5: Documentation check
echo "[TEST 5] Checking documentation..."
DOC_FILES=(
    "${PROJECT_ROOT}/README_OPENBMC.md"
    "${PROJECT_ROOT}/scripts/build_openbmc.sh"
    "${PROJECT_ROOT}/hardware_spec.txt"
)

for file in "${DOC_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "✓ $file exists"
    else
        echo "✗ $file not found"
        exit 1
    fi
done
echo ""

# Test 6: Configuration validation
echo "[TEST 6] Validating build configuration..."
if grep -q "ROC-RK3568-PC" "${SCRIPT_DIR}/build_openbmc.sh"; then
    echo "✓ Board name configured correctly"
else
    echo "✗ Board name not configured"
    exit 1
fi

if grep -q "rk3568" "${SCRIPT_DIR}/build_openbmc.sh"; then
    echo "✓ RK3568 SoC configured"
else
    echo "✗ RK3568 SoC not configured"
    exit 1
fi
echo ""

# Generate validation report
echo "[REPORT] Generating validation report..."
cat > "${PROJECT_ROOT}/VALIDATION_REPORT.md" << EOF
# OpenBMC Build System Validation Report

## Validation Date
$(date '+%Y-%m-%d %H:%M:%S')

## Test Results

### ✓ All Tests Passed

1. **Build Script Syntax** - Valid
2. **Help Command** - Working
3. **System Requirements Check** - Passed
4. **Hardware Specification** - Available
5. **Documentation** - Complete
6. **Build Configuration** - Valid

## System Information

- **CPU Cores**: $(nproc)
- **Total Memory**: $(free -h | awk 'NR==2 {print $2}')
- **Available Disk Space**: $(df -h /workspace | awk 'NR==2 {print $4}')
- **Git Version**: $(git --version | awk '{print $3}')
- **Python Version**: $(python3 --version | awk '{print $2}')

## Board Configuration

- **Board**: ROC-RK3568-PC
- **SoC**: Rockchip RK3568
- **CPU**: Quad-core Cortex-A55 @ 2.0GHz
- **Architecture**: ARM 64-bit

## Build System Features

### Implemented Features
- ✓ System requirements checking
- ✓ Dependency installation
- ✓ Git configuration
- ✓ OpenBMC repository management
- ✓ Build environment setup
- ✓ RK3568-specific configuration
- ✓ Multi-stage build process
- ✓ Build manifest generation

### OpenBMC Features (after build)
- ✓ Web Management Interface
- ✓ IPMI 2.0 Support
- ✓ Redfish REST API
- ✓ SSH Remote Access
- ✓ KVM over IP
- ✓ Virtual Media
- ✓ Sensor Monitoring
- ✓ Firmware Update

## Known Limitations

### Resource Requirements
- **Minimum RAM**: 8GB (current: $(free -h | awk 'NR==2 {print $2}'))
- **Minimum CPU**: 4 cores (current: $(nproc))
- **Build Time**: 2-4 hours depending on resources

### Recommendations
For optimal build performance:
1. Use a system with 8GB+ RAM
2. Use 4+ CPU cores
3. Ensure stable internet connection
4. Have 50GB+ free disk space

## Next Steps

1. **Install Dependencies** (if not already done):
   \`\`\`bash
   ./scripts/build_openbmc.sh --deps
   \`\`\`

2. **Clone OpenBMC Repository**:
   \`\`\`bash
   ./scripts/build_openbmc.sh --clone
   \`\`\`

3. **Configure Build**:
   \`\`\`bash
   ./scripts/build_openbmc.sh --configure
   \`\`\`

4. **Build OpenBMC**:
   \`\`\`bash
   ./scripts/build_openbmc.sh --build
   \`\`\`

## Support Resources

- OpenBMC Official: https://github.com/openbmc
- Rockchip Wiki: http://www.rock-chips.com/
- Firefly Forum: https://www.t-firefly.com/

---
Generated by OpenBMC Build System Validation Tool
EOF

echo "✓ Validation report generated: ${PROJECT_ROOT}/VALIDATION_REPORT.md"
echo ""
echo "========================================================================"
echo " All validation tests passed successfully!"
echo "========================================================================"
echo ""
echo "Next steps:"
echo "1. Review the validation report: ${PROJECT_ROOT}/VALIDATION_REPORT.md"
echo "2. Read the build guide: ${PROJECT_ROOT}/README_OPENBMC.md"
echo "3. Run full build: ./scripts/build_openbmc.sh --all"
echo ""
